/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sg.hackerrankalgorithms;

/**
 *
 * @author jonat
 */
public class Billboards {
    public static void main(String[] args) {
        
    }
    
//    public static int billboards(int k, int[] revenue) {
//        
//    }
    
}



// ADZEN is a popular advertising firm in your city that owns all n billboard locations on Main street. The city council passed a new zoning ordinance mandating that no more than k consecutive billboards may be up at any given time. For example, if there are n = 3 billboards on Main street and k = 1. ADZEN must remove either the middle billboard, the first two billboards, the last two billboards or the first and last billboard.

// Being a for profit company, ADZEN wants to lose as little advertising revenue as possible when removing billboards. They want to comply with the new ordinance in such a way that the remaining billboards maximize their total revenues (i.e., the sum of revenues generated by the billboards left standing on Main street).

// Given n, k, and the revenue of each of the n billboards, find and print the maximum profit that ADZEN can earn while complying with the zoning ordinance. Assume that Main street is a straight, continuous block of n billboards that can be removed but cannot be reordered in any way.

// For example, if there are n = 7 billboards, and k = 3 is the maximum number of consecutive billboards that can be active, with revenues = [5,6,4,2,10,8,4], then the maximum revenue that can be generate is 37:
// 5 + 6 + 4 + 10 + 8 + 4 = 37.

// k: an integer that represents the longest contiguous group of billboards allowed
// revenue: an integer array where each element represents the revenue potential for a billboard at that index

// Input: The first line contains two space-separated integers, n (# of billboards) and k (the max number of billboards that can stand together on any part of the road). Each line i on the n subsequent lines contains an integer denoting the revenue value of billboard i
// Output: Print a single integer denoting the maximum profit ADZEN can earn from Main street after complying with the city's ordinance.
